var folder = "../img",
    images = [
      "ISM_Awareness.png",
      "ISM_BelieveIt.png",
      "ISM_DogFood.png",
      "ISM_EveryClient.png",
      "ISM_EverySecond.png",
      "ISM_FigureItOut.png",
      "ISM_IgnoreTheNoise.png",
      "ISM_Inches.png",
      "ISM_Innovation.png",
      "ISM_MoneyFollows.png",
      "ISM_Obsessed.png",
      "ISM_Pennies.png",
      "ISM_RightThing.png",
      "ISM_Roast.png",
      "ISM_Simplicity.png",
      "ISM_Urgency.png",
      "ISM_WeAreThey.png",
      "ISM_WhoIsRight.png",
      "ISM_YesBeforeNo.jpg"
    ];